import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

import connectMongo from '@/utils/connectMongo'
import Test from '@/models/test'


const inter = Inter({ subsets: ['latin'] })

export default function Home({tests}) {

  const createTest = async ()=>{
    const randomNum = Math.floor(Math.random() * 1000)
    const res = await fetch('api/test/add',{
      method: 'POST',
      headers: {
        'Content-type':'application/json'
      },
      body: JSON.stringify({
        name:`Test ${randomNum}`, 
        email:`test${randomNum}@test.com`
      })
    })

    const data = await res.json()
    console.log(data)

  }


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <button onClick={createTest}>Create Teste</button>
          </div>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>


          {tests.map(test=>(

            <a
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
              key={test._id}
            >
              <h2 className={inter.className}>
              {test.name} <span>-&gt;</span>
              </h2>
              <p className={inter.className}>
              {test.email}&nbsp;API.
              </p>
            </a>

          ))}

        </div>

      </main>
    </>
  )
}



export const getServerSideProps = async ()=>{
    
  try {


    console.log('CONNECTING TO MONGO')
    await connectMongo()
    console.log('CONNECTED TO MONGO')

    console.log('FETCHING DOCUMENT')
    const tests = await Test.find()
    console.log('FETCHED DOCUMENT')

    return { 
      props: {
        tests: JSON.parse(JSON.stringify(tests))
      }
    }

  } catch(error) {
    console.log(error)
    return{
      notFound: true
    }
  }
}


